- name: Update Windows
  hosts: ansible-win2k19
  remote_user: administrator

  tasks:
  - name: Install Windows Update
    ansible.windows.win_shell: .\install_update.ps1 -KBNumber {{ KBNumber }} >> C:\Code\install_update\install_update.log
    args:
      chdir: C:\Code\install_update
